"raffle pala to! haha randomizer, di'ba nakalimutan ko pa sabihin lolol."
"salamat nalang sa history ko, if magka history about canada dito hahahhahahaha."
"double date ng elviarkin when iowfbgo pero aw di'ba!! kakamiss nvrfg pero no worries, feel ako magpapakita sila soon sa oye."
angelica vasquez ikaw na bahala sa kumunity decides char.
tamad aq mag edit now but--.
yun lang din kasi naisip kong paraan kasi ang lungkot talaga ng mga tao noon.. kahit ano nawawalan na rin ako ng pag asa pero pag naaalala kita at yung mga taong importante sa akin.
and dont get me started sa twinkle at dancing queen gurl kulot na kulot at birit na birit hiyang hiya na ang cheese curls sa ganda ng mga kulot nya teh.
"not to be insensitive or what but there are nights talaga where i wonder what kind of aus pa kaya yung magagawa ni miss 99misfits if hindi siya nag-deactivate. coz yk, fallacy's the first and only au of her that i've read and i learned alot talaga. i just hope she's doing good."
"nay!"""" Kikilos na sana ang nanay ni Baekhyun para kuhanan ng shampoo ang anak pero pinigilan naman ito ni Sehun. """"Tita ako na po. Pagpatuloy niyo na lang po pagluluto niyo dyan."""" """"Ahh osige"
di'ba ma hahaha worth it din pala.
so ano talaga ang totoo potanginuh.
hoy pinutol ko 2hrs kong tulog para sa tkcs tapos malalaman kong 6am pa yon?
hahahaha send packing vid naman diyan hahaha.
di'ba ate. medyo lumiko na naman tayo ng landas hahahaha.
oki patapos na ako sa sinusulat ko maam sorry if ikaw think i was bragging pero ulit ulit naman tayo eh mula simula sinabi ngang di ako mapaborito na tao hirap na hirap ako lagi sa subject mo.
pero sa later stage or phase ng trainee journey yung mismong before debut
saklap beb hahahahah buti nlng tlga magaling siya sa actingan apapa pledge ang mga inays kahit papaano nadadagdagan ang kaban laugh out loud.
di'ba blinding lights was the most streamed song in 2020 tas it got robbed.
feeling ko may ida-drop mamaya.
kahit ako nabwisit parang sinasadya eh tampalin ko yon.
feeling ko talaga si chang yoon ang stalker. baka naiinis na siya sa kakulitan ni rocky. char lang! jusmeyo. pinapasakit lalo ng fmiyc ang ulo ko.
pwede po pareserve?
oh well yung ibang nominated lalo na sa record of the year and song of the year nga di ko gets bakit kasali eh wala naman masyado ganap.
"yung sequence ni parang kasabay nung music sa background. relaxing, soothing na ayun paplakda ka sa tulog. nagising nalang ako nung tinanong ako kung okay pa ako. isa sa nagustuhan ko yung massage sa legs and paa. sapatang pressure pero wagas tanggal lamig."
may pa ako a portion sila oh my god.
just thinking about how many trainees did not get to debut just because they did not fit the image of the group the company wants to think na ininstill sa kanila yung thot na makakadebut ka lang pag nagwork hard ka (meritocracy) wll it's tru na kailangan nilang kumayod.
did just kumi said she studied english in cebu 5 years ago?? did i heard it right?? i keep replaying it.
ang cute talaga ni chimon gagii.
cutie talaga.
bitbit namin sama ng loob natapos ang live namin kanina para sa grammy nomination na yan tas ayon lang yon? fvk scammys.
parang hahanginin nanaman yung pera ko.
"di ba dpat protektahan ang ate mo?"""" Peru wla nmn nagawa to #ViralConfessions @RCDNarratives"
Alam ko! More than anyone
"last exam na sana today, parang sasakitin na ako kapag may nag-announce pa."
ang gwapo mo talaga attorney. sana makita ka namin ulit na kagaya yong ngiti mona kasama mo pa si ate mahal. wemissyoumahmygz.
goku nmn may uaasapan us dba.
"so may teaser na mamaya, di'ba?"
di'ba pwede sabihin kay sir na nilindol yung lote kaya di ako makagawa ng floor plan.
nag tanong lang naman ako kung si harley bayun sabay sabi ni kuya harley parang kailan lang kinukuya mo pako ah sorry my false atleast di nakalimot bleehh.
at panatilihin po natin na sumunod sa safety protocols ayon sa iatf guidelines. maraming salamat po!
gigising ako ng maaga mamaya para sa inyo mga mahal ako.
te kahit ung italian comm ng vbw pede na! ishikawa ng ishikawa hahahahaha.
tangina mo.
sinanay lang pala tayo saglit after nun wala na huhu naisip ko na yan eh sabi na'nga ba.
Denmark & Romania mas mababa population kesa sa pinas pero ung ratio ng infections nila based on population compared satin ang laki.
onsehan na.
para sa pag babago kay ping tayo.
so pag di'ba maganda boses masaya kayong tingnan pinagtatawanan yung ina idol lang niyo yung may talent at kaya niyong anu pa sabihin niyo kat k para sakin talent yun at para sakin magaling siya.
hahahhahahahaha ampota talaga.
"baka maging ia na ulet ako dito since simula na talaga ng 2nd quarter, kailangan ng magseryoso."
doc bigla ko nagulat kay gamay raman bisaya ngare i forgot ikaw spoke bisaya.
to:00 am thoughts dali.
para akong katang sa ilog na hindi na alam kung saan ang tinatahak dahil nakatingala lamang at silaw na silaw sa iyong liwanag na parang araw.
true ganda pa bgyo gelo concept art.
di'ba?? so anong merit nung pa speech nila at the start? kaka-init ng dugo.
tapos nag announce sila isang category lang.
ha?
grabe mga deadlines ayaw akong takutin haha parang gago hoy ayusin niyo 'yan.
hahaha. ohhh di'ba.. beke nemen.
di'ba wednesday na?? does that mean kahapon pa yung pics?
"they were insisting na damage 'daw' yung stem cuts sa applehoon that i was selling. also, the fact that they counted the stem cuts i sent all my other bo pcs since ayun talaga issue sa pcs from bo sobrang daming defects and all krazy manufacturer."
hindi ko na rin alam navivisualize ko na kung sino sino basta ang sure tayo andyan si jungwoo di naman maitatanggi.
ayy parang tanga yuns
"nag aalangan nga akong gamitin kasi korean names ang madalas kong nagagamit lang yohan, daniel tsaka yung mga alam ko yung english name na idols mapag lagay kasi ako ng name pero nauubusan na ko ng pangalan hahahaha."
mas cheap di'ba yung di man lang nagpaligaw ng matagal? nakipag live in agad?
di ako mababan dito beh sa bait kong to hahahahha unless may ituro ka saken na aawayin ko. ingat naman lagi pero pag sinumpaang tungkulin ay ready naman ako worst case scenario.
na-confuse nga ako kasi di'ba yan?
kilala mo di'ba hahahahaha.
"why naman nag mura, essa?"
hinahanda kayo para mas maging masaya at mas matibay ang pagsasama niyo kung magiging kayo man sa huli pero siguro naman di'ba sila?
god fearing candidate siya di'ba?
alam mo kung ano ung problema? masyado ka naging busy bilangin ung mistakes ng mga tao sa paligid mo na halos di mo na napapasin ung mga mabuting bagay na nagawa nila para sau.. tao lang din cla kung may pakakamali p pagkukulang man sila ganon ka rin.
oh my god bestie talaga kita.
feeling ko pag nakajowa si jungkook madami magiging broken nako hoonie tumigil ka dyan.
sumpa ke talaga ing kape nayta.
di'ba nga marami sa mga job hiring ay pagandahan pa ng kanilang cv. asahan nating ganun din dito sa mga naghahangad na maging (at iba pang posisyon) trabaho nating kilatisin ito. sino ang maayosmatino? sino nagpapanggap? dito masisilayan ang kanilang kakayanan.
di'ba pwede beer.
haha supportive naman to.
tangna sana next year dikana gnyan katoxic tanga uso magbaba ng pride tangna mo ikaw na'nga may atraso saken pero pinalagpas ko nalang pero yawa ka pangit sa gnyan ayaw magbaba ng pride parang gago lang tignan natin kung may makakausap kapa samin magtotropa.
ilang araw na kung puyat dahil sa panunuof ng ls. pero parang ngayon mas lalong hindi ako makakatulog.
373 luiz kalma ulit please.
kaya ka ba may girlfriend? huh? kaya ka ba may girlfriend para maisantabi feelings mo para sa kanya? napahinga naman ng malalim si chanyeol at naglakad naman siya papunta sa ref para kumuha ng yelo. nung una pero ngayon gusto ko narin naman si riki.
parang mga tanga! ang bobo talaga ng grammy gosh nakaka loka.
pero the details tangina but where do i wear this? can it fit in my shoe closet?
"uhhhhh, 3 na'nga lang, 3 din sa iba eh."
gusto ko lang kiligin.
"yung ka work ko na lalaki si jas, kwento siya about sa plan nya this dec tapos ako sabi ko wala pa. siya sabi nya mag out of town siya with bibi daw hahahaha naols diba kuya jas sa gf nya talaga maiinggit lahat eh, hindi yung jowa nya yung mag ooverthink kung kanino."
ratio is 3 wins over 5 aoty noms oh my god.
di ako natutuwa talaga.
Merry Munchkin
"it's yet another moment for me to work and develop my character. lately, medyo blurry na tayo. madaming taong unintentionally nasaktan with unresolved issues. di tayo ganito, parang walang pinagkatandaan, ace."
yung urine test di daw sila maniwala.. parang gusto nila habang umiihi si bbm nakikita nila.
parang kinagat ka lang ng aso
di'ba pwedeng mayaman nalang agad?
di'ba masarap ulam jan lods?
ang hilig sa wipe talaga tommaso.
"correct, because that was a self-defense case. as you can see, in murder cases, victim is routinely used."
si naruto kaya marunong.
mukhang ganon na'nga hahahahaha para sa enha magpupuyat.
pumunta lang talaga kami sa okada para mag kape.
"hindi rin gusto ni justin na makipagsumbatan kay ken. ayaw niyang mag-away pa sila nang malala ngunit kung magmamatigas ito ay hindi siya magpapatalo. i was out there. fighting to be here, jah. fighting to be with you. tapos ang gusto mo pala eh iwan na lang ako rito?"
wts lfb twice lightstick cbz version to ph full cod.
humihinga lang dahil uso po.
kaya pala kanina ang tahimik nitong jiririts na toh sa turn ni anji sa football. paghihiwalayin ulit ang kyji.
"madadaan naman ata to sa dasal, di'ba?"
oh di'ba kakaopen ko lang ng ulet may na mine na ko agad.
talaga ba? picture mo nga.
pahingi naman ng tutorial kung paano maging.
ayaw po ata nila ng tamang sagot.
"ive been in so many fandoms before but never have i felt this connected with my idolsmains. and it made me think, kpop and anime kasi un. its from different cultures. syempre, they still hold a special place in my heart. i still love all of those that made me happy."
quota na daw si taylor sa grammys eh hahhaha charrr.
noooo hindi po.
"ba't ganooooon, ako lang ba?? parang kaunting kaunti na lang magkamukha na silang dalawa ni miah at dons."
buti bhe at sinagot mo.
di'ba kayo nanonood sa grammys?
isasama mo pa yan sa ulam nyo
i love this conyo jared since day 1 talaga.
parang gusto na kita pakasalan
parang nakatambay laang.
mga oldies na kasi mga taga davies hahaha.
gusto ko mag-kalat 'di'ba puwedeng mag sex nalang agad si akira at ravi.
hoy totoo so much ahahahahaha.
"kahit preorders na bukas, kung di ako makakakuha ng pc ng mga bias ko, edi bye."
kala ko tuluyan na masisira araw ko dahil sa mga naging exams buti na lang na-credit na. sabihin mo salamat tdp!
di'ba? kung dun binabase.. ang ideya ng upuan. o ng pwest0.. kung sa pul!tika sa kanila nagumpisa? ganon ba? tama ba ko?
fav era ko talaga b:c
ung inaantok kana tapos ganyan pa sila mag.
takang taka rin ako kasi ayun lang wala di'ba?
"what they went through just to get to where they are now. pure hardwork and determination, which is why we cant help but support them and in return, they also support us mentally. kahit hindi nila tayo kilala isa isa, kahit hindi nila alam lahat ng kwento natin,"
arog kaan. may initiative.
oo haha kilalanin mo binabangga mo.
ano ba naman yung mag live kayo di'ba.
yung chef ka tapos adonis dancer ka pa hahahahahahahahaha.
ano?? bakit ano?? di'ba yon tao?? nuyon aso?
pano mo nasabi? may conclusion? di'ba nagtatanong?
ang demanding ah!
HAHAHA so nag space si tita jin buti naman may happy pill nanaman ako #5GSpace
"yes di ko kayang magtanim ng galit or sama ng loob mas lalo ko pang pinagpray yong mga taong nagawan ako ng mali.. di'ba sabi ng lord kung makapito man nagkasala sau, makapitongpotpito mo din tong patatawarin ganon paniniwala ko kaya di ko kayang mgtanim ng galit."
hi kung my time ka siguro visit mo st luke's and verify mo kung talagang pumunta si bbm para mag pa test hahaha.
sino nanaman yan enaka.
Ken. Wag ka nang lumapit
and also ngayon hahaha.
luh bastos di naman nakahubad.
so ba't mo nilike.
yan gumawa actual talaga e ung isa puro virtual vlog dito vlog dun pero nakapag taka di vlog ang pag dwagtet nya.
"other hms said before that anji is not responsible for kd pero bakit parang you obliged her now for his feelings. she cleared everything with kd naman na, tama na yon."
kanina watching playhouse nakaka chubby ng puso ang mga comments ng mga tao abt sa donkiss at the same time nakaka hinayang hayss mnagemnt :'( 
shhizzz. yung aksidente mong nabuksan yung gc niyo kung saan 'di ka nagpaparamdam.
hooooy yawaaaa talagang k-drama pala talaga to. hahahahhahahahahahah.
oo hahahahahah parang mga little sisters lang tayo ni shane pabili po ng pcs ate hahaha soon to be official with crushie pero ako lang may alam hahahhaha.
kung nasaan ang St Lukes which is under the jurisdiction of Brgy. Fort Bonifacio
ang gwapo talaga ng 10.
di ko na tuloy alam kung gusto pa ba ni anji yung ginagawa niya. kung totoo ba niyang naeexpress yung sarili niya. o sumusunod nalang siya sa gusto ng housemates na gawin niya. hindi natin alam eh. kasi takot siya mahusgahan. kaya please lang. hayaan niyo siya matuto na siya lang.
sobrang blessed ko talaga na meron akong super bait na tl and love na love ako.
ask ko lang mga future educators sa tabi tabi di'ba kayo nauubusan ng name na ilalagay sa lesson plan or ako lang talaga mapag lagay ng pangalan sa lesson plan? hahahaha.
they're just the mananalo pag in and popular they aren't the same grammy na tlga hahahha.
follow back ko ba?
syempre kaya nga lodibabes kita eh sept 27 libras lang naman red flag sa sign natin eh.
ulitin ko! survey lang!? okay lang ba mag message sa ex? may ire recommend lang sana ako na kanta?
oh di'ba sheeet that's why i'm having deja vu kanina because of that waking up scene namiss ko si nana liit.
kahit ano pa sabihin mo ikaw talaga mas mukhang drug adik at magnanakaw kesa ky bbm hahahaha partida hndi ka nagpa drug test sge libre drop drug test dito.
ah talaga ba? sino ka muna nyehe.
"yes, private hospital yan mga pro for vip treatment."
at kht busy kme gumagawa talaga kme para kht paanu my update kme at nag ppray kme nasa matigil na pag babash ky kyle dhil sa simula pa lang marami na sacrifice si kyle at sana un ang maalala nla.
baka di nakapag-shoot si ate girl dahil nag-quarantine.
unfair? or baka sadyang di lang para sa'tin.
uy di'ba taeyong din na pull mo?? teka sticker album ba yon?
- hindi gago - kiligin na ba'ko be? - bukas na.
mas nakakapagisip talaga ako pag madilim paligid haha.
o kala ko ur out?. ano pa ginagawa mo dito? free francine diaz.
"they were insisting na damage 'daw' yung stem cuts sa applehoon that i was selling. also, the fact that they counted the stem cuts i sent all my other bo pcs since ayun talaga issue sa pcs from bo sobrang daming defects and all krazy manufacturer."
his hometown. gmanetwork.com/news/topstori…
ate hazel baka naman palagay ng dt deanna wong.
"di naman po sa pagmamalabis, pero sana in the near future, spicy naman po. hahahaha! ang demanding ko di'ba? e di pa'nga daw available sa iloilo now. hahahahaha!"
"haha oo dai, ragdoll pusa nya. si sunny yun yung unang bet ko na thai reason bakit ako pumuntang thailand at nameet ko yung friend nya. siya yung sa i'm fine thank ikaw love ikaw at sa my ambulance, si bright yung batang sunny don."
oz to day concert pass ga simple ulit. click the link and drop your username! link closes 6pm friday. favor! naman kayo ng votes nyo sa rawr tapos reply nyo dito. labyu.
"looking for the uv express driver who brought me home. since i was in pain and dazed, was not able to get hold of his name. but he was able to have a pic with me i remember. owe him a lot. as i was alone there sprawled on the street. luckily he passed by and i flagged him."
parang therapy yung ngayon.
"o di'ba?tatlong units nakaopen youtube ko recording acad pero dahil sa trauma dala ng ginawa nyo last year di ko kayang. god is good, bts will be nominated in various categories and will definitely win all of them this time!"
pangit mo kabonding pakyu haha.
is nominated in all of the big four categories at this years.
"lantaran lang talaga si guramis, laughing stock na sila years ago mas lang ngayon. bts will always be the standard. ehe, whipped yern."
"malapit ng mag dec, konting kapit nalang lods."
siempre naging busy ako di pa tapos review ko kay if i were to rate the overall experience at location 1010 1010 vichy (matteo) 1010 massage (jomar) 1010 affordable quality massage.
okay naman siya ha. hindi cheap ang dating. parang mga swimsuit lang naman na very sexy. saka ganda niya ha. blooming. ganda pa ng shape. she needs to grow up already. tanda na niya noh. di na bagay pasweet. saka mganda naman mga kuha. masasanay ka din.
simple edit lang to para sa inyo.
another episode of being scammys! i hate grammys talaga panget tuloy ng gising ko.
di'ba nakakaramdam tong tatay ng tutee ko na di ako natatawa sa mga daddy jokes niya hahaha.
lah di'ba pwedeng puro kilig lang umiyak.
"akmang kukunin ni xander ang mga pictures pero pinigilan siya ni ken at itinulak palayo. fuck, akin na 'yan! wala kang karapatang wala akong karapatang kunin ang mga mula sa cctv na nakakita sa katarantaduhang ginagawa mo sa pamilya ko? pagtutuloy ni ken."
nakakatakot pala maging malungkot?
inspiring siya huh. HAHAHHAHAHAH
di'ba pwedeng 2022 nalang? chz.
i did my best naman di'ba? but why is it still not enough?
hahahahah wala talaga pumasok sa isip koo sorna.
dapat dba a month before remind na. nku kung d pa mag email ung hr sa pending wala talaga.
"sabi na may kapalit pag sobrang saya okay na okay na cla, di'ba nila nakikita yun? yun na ang iniiyakan ni anji eh, yung hindi nila maintindihan yung samahan ng kyji, hndi ma nya alam papano kikilos, saan lulugar. please help huhu may date pa cla eh."
pinag iisip pa ako ni woosung di'ba pwede i-reveal nalang.
mga ot4 talaga mga paladesisyon eh.
i mean sa relasyon pag sa ibang sitwasyon my nasaktan din akong damdamin.
sana all in bisaya is unta tanan right? sakto ba?
may nag kick out kay hoonie sa space (not exposing space baka icancel ako dito ineexpose ko sila hah.).
ang tangina ni sevi at riri talaga.
"lumapit si justin sa anak at niyakap ito. pumulupot naman ang braso ni sebby sa bewang ng taytay niya. m-mad ba kaw taytay pag sabi ko sosowi ako kay dada ko? sabi ko kasi kanya h-hate ko siya. taytay, di ko po siya hate. lalabs ko dada ko eh, humihikbing saad ni sebby."
isa pa yan. issue ko na yan dati. akala ko lang iba tlaga ang reviews at policies ni grammys baka ndi pasok bsb naten sa mga categories. pero sold out concerts til now. something is not right lalo na ung millennium album nila na tumabo tlaga sa sales pero ndi manalo sa kanila.
as in bihira lang sila mag-nominate.
bat ganon sobrang saya ng mga bata kanina pero tangina diko talaga kayang sumabay sa saya habang malungkot ako.
promise nakakabaliw at masasanay ka rin na minsan lang magka update from the boys hahahahaha.
nag spaces pa kau!! leche.
cancel onyonyonyo 2g siya today.
biggest slap to that industry plant laugh out loud di'ba kinaya buhatin?
"sino ba nanggugulo? if si bbm tinutukoy mo, name something that he did,bakit nasabi mong nanggugulo pa."
yan coffee ko dito sa bahaaayy! 🤩
hahahahaha di'ba pwede idaan nalang sa kiss?
baka dream talaga kasi.. of dream? eme.
piano parang gusto pa ata pumalag for paris 2024 hahahaha.
cancel mochi daw kasi anak nya lang daw si nishi tapos hindi daw si beomii.
anong vid yan? pa send po link. kung ano ano nalang talaga ung ina accuse kay chie. 25 na po si chie. do you think interested sha sa lt? nakilala sha as herself not as part of any lt.
ang cute ng twinote nag dl aq hahahahhajajaja.
Pharmally scandal at sandamukal pang scam at korapsyon sa gitna ng napakraming namamatay ngayong pandemya? 'Di ba nasa kanila ang pera? Sila rin nagbukas ng mall
"one of the biggest lesson ive learned this 2021 talaga is that no matter how you planned your life, if its not gods will then it will never happen."
may tira pa. A bit pricey but hindi na ko nagcecrave ng yosi. For now. Sana magtuloy tuloy talaga wahahahahaha.
"pansin nyo ba? bakit kapag bbm caravan bihira ang for-wheeler vehicles, mas maraming motorsiklobike. bakit kapag kay vp leni maraming for-wheeler?"
"missyou bestieee sorry ia, lubog na lubog talaga sa acads aaaaaaa labyu."
"wala nang nagawa si xander kung hindi ang pagbuksan ng pinto sina ken at josh. ayaw naman niyang gumawa ng eksena sa labas ng bahay. nang makapasok sa loob ay agad ding nagsalita si ken, mmm, you're living in a decent house. you're also a cpa, am i right?"
lakas talaga ng chemistry ng dalawang to may naalala akong hindi din mapaghiwalay nung chanacc days.
sana i invite ni kuya sina at sa bahay niya tapos sila kumausap kina anji at kd. sila mas nakakaalam sa kung anong meron ang kyji. please.
as if naman mananalo si leni more!
active hour ni heeseung is 2am at gising ako para sa kaniya.
di man ko ganahan ana niya bisan pinoy pana siya hehe.
bet ko yung pareho nating profile pic si pp kase siya talaga dapat pero mas nagsisimp na din tayo kay billkin these days ahahahahha.
talented naman mga jowa ko te bts tsaka enhypen ehe oh 'di'ba.
nakakahiya sila sobrang babaw talaga.
"grabe, pati result ng drug test fake. kung talagang gusto nya patunayan na nagpa drug test siya, ipakita nya sa media habang kinukunan siya ng specimen or yung mismong hair nya nalang para mas accurate."
kuda ng kuda 
spam yan mali-mali grammar. di'ba malalaman ang spam mail or anything similar sa grammar and spelling?
parang nagiging bente nalang wankey ngayon ah.
dalawang araw nako sa master for. may sumpa talaga.
di'ba nila nadeserve?
"parang yung ibang housemates rin need magset ng boundaries sa pahihimasok sa buhay nina kd at anji. gets ko na concerned kayo sa kanila, pero you don't really know them pa. hindi niyo alam kung ano ang foundation ng nila. kaya please lang, kawawa na sila emotionally."
naiiyak ka na ba dyan.
"noong sl at sh, hindi ko pansin yung similarities namin ni marem sa ugali at actions. pero nung tsh na, shet parang i found my twin."
i'll be okay kahit na ako lang mag-isa because i'll have our baby! -dom our baby? sigurado ka bang akin 'yan? hindi kaya 'yan anak ng lalaki mo? -gavin.
I'll def buy season's greetings 
today with si as usual. full video soon.
gago oo nga yaan mo na putanginag dmi dmaing twts eh.
sumasakit ulo ko sainyo. parang need ko ulit 1 cup. dejoke naka anim na ko.
ang gulo gulo ng wts tags grabeee di'ba kayu nauumai.
goodmorning ganto pala feeling ng iniwan.
mali ang mga intelligence mo po tatay digs.. love ikaw po wala ng iba p.
di'ba angst to e ansakit taena yan.
nasa gubat naman di masyado amoy hahahhaha.
"wala na'nga atang laman, hayup."
my power trio!! syempre di pwedeng maligo nang wala silang tatlo.
mabalik talaga akong cod pag summer.
kukulit naman kase di'ba makaramdam na ayaw sa inyo mag open nung bata?
93 in thiz houz paladesisyon uz.
"outdated na sila, kaya slim na ang chance sir."
feeling ko bagay ung ganyang tunog sa tagalog o kung anumang wikang gamitin hahah. medyo mala jpop din na dating ganon idk kasi etong kanta ng mnl48 (imagine niyo na lang na hindi mala-japanese ung pagbigkas nila bat ba kasi pinaganon ng direk nila laugh out loud).
haahhahahaha bilis talaga pag pag kain.
hindi na ako makatulog. ngayon lang sana ako babawi ng tulog kaso biglang parang ang dami kong dapat iconsider.
"ilang araw nang tahimik ang bahay nina justin. sebby is not talking like the usual. justin thought that maybe his son is still affected by the fight he had with his father. sebby, let's eat. mmmkay po, taytay. palaging ganyan, tipid magsalita. parang walang gana."
di ko rin maintindihan kung bakit kakaiba nararamdaman ko sa iyo di ko maexplain di ko alam kung maiinis ako o matatawa o ano.. ah basta kakaiba.
apaka cutie talaga ng bebe ko.
dun ko kinukuha yan. yun lang lakas ko para mag-ipagpatuloy pa ang buhay.. wala naman kasi ibang choice.. iloveyou!
"kingina 'di'ba masaya buhay ng mga 'to, tabi nyo na ako na jan."
di ko na kaya yung 6am sana alas tres na lang talaga kasi for-5 naman lagi sleeping time ko (.
bt parang ako pa mali.
comment: hays nakakakilig talaga sila.
tangina.
minsan kailangan mo nalang talaga kalimutan yung feelings mo para sa kanya.
wait di'ba si kang sora yung partner ni papi sa warm and cozy? halaaaaa lahat ng nakaka-partner ni papi kinakasal naaaaa!! susunod na ba?
dapat talaga sa mga fake binabasura.
"non-athlete here pero to these organizations, di'ba kayo nababahala na how many sportsmen hace changed their citizenship because of our system? peraan na lang? hindi ba iko-consider how much the athletes spent their pockets while you're aiding them as small as grain of rice."
are you from?? if yes baka kasi sa 25 nov. pa talaga tayo. parang sa korea pa nag start.
bakit naman ang lungkot lungkot nila mag announce di'ba sila happy sa bohai nila.
dagdagan ko pa pra magkabonus ka galing intel fund.
"gigising ng 6am para sa 4mins performance video, yes."
its like saying that st. lukes medical center is not an accredited drug testing center. baka magalit sa iyo ang pathology department ng st. lukes.
ngayon ko lang nalaman na may 1 hour limit lang ang ig live wtf?
"hi! feel free to message me in here, kasi natatabonan mga dms nyo kaya here nalang )."
loe po.
hahahahaha ang kalat di'ba ate.
walang kwenta yang librong yan. low-key degrading feminism. nag trend lang dahil sa mga ig posts na mala minimal.
pilitin nyo ko.
- himala - tuloy mo daw be.
"ask her what? do ikaw even know what the trend is for? if not, try to not meddle. free francine diaz."
parang may lamay sa grammy eh noh antamlay magsalita di'ba kayo naka kaen.
halaaa atee! ang galing mo talagaa! palagi po akong naiiyak at namonotuvate pag naririnig ko sa playlist ko yun! good luck po sa djooky!
kunting araw n lng bunso makikita kana ulit namin wemissyoumahmygz.
ang ganda mo kanina.
Ken. At gustong gusto ko rin na samahan ka sa laban mo. Gustong gusto kong hawakan ang kamay mo hanggang sa makawala ka sa kumpanya mo. Kung ako lang
hayy la seokjin talaga.
ganun talaga. makalat tayo sa ganyan.
nakakahagard talaga pag aaral ng mabuti chz.
"mellow touch, istasyon ng mga motel di'ba? puro love songs."
parang di ko kaya ngayon hshs.
isa talaga akong clown.
try hard nanaman magpatawa parang gago lang.
"para sa impormasyon tungkol sa iyong aplikasayon sa ng programang panlunsod, bumisita sa: (33)."
ito pala full version. di ko alam kung bakit nacut huhu basta ang funny yawa.
"bet bongbong marcos says he has undergone a drug test, submitted results to pdea following blind item of president duterte on an alleged cocaine user among candidates."
ang ganda di'ba hahhahaha.
hahahahahahahahahahaha ang gwapo ng nag s-serve si 10 putangina daddy.
cute po ng username nyo parang sans rival hahahah.
preprocessed_text
lakas lng ng loob n'yong mambash.. di n'yo nga maipakita yang mukha n'yo e
"korek beshy, at hindi lang sa isang artist nangyari yan, marami na sila.. kung mahalaga din ang artist nyo sa inyo, protect them too. kawawa naman ang mental health kapalit ng isang contrata, kung sa bagay pwede nyo ibalik yan, kasi pinirmahan nila yan at alam nila consequences."
wala man lang promo buti na lang mas masisipag mga airens!
as if manalo se ka leni?
di'ba pwede makita sa cctv?
"lord, sign na ba to? char."
ka-miss kumarat. kalat. eme.
baka next episode pa.
pero tbh friends kami ni sunny irl active lang talaga kami masyado dito sa twtr di kami nag uusap sa messenger hahahahahaha.
ganyan yan. pero panigurado mamaya pag mag-isa na lang ulit yan iiyak na naman yan. edi wag mo iwan mag-isa. samahan mo matulog sa kwarto niya. luh sira ka ba? never pa'nga akong nakapasok sa kwarto niyan. luh talaga ba?
di'ba.
"ay hindi,now lang talaga yan para sa edit hahahaha jk."
kaya nga ahaha! kahit anung meeting gawen mo. kinabukas wala nanaman alam haha deanna wong.
"alam mo kung ayaw nyo ung tao do not vote for him, parang ang talino mo. pakialam nmin kung doon nagwork relative mo. research ka muna bago ka mag accuse. yan ang format ng mga drug test - walang pagandahan ng itsura. use your brain."
napaka toxic ng grp ng axie market bye.
puyat ka talaga kakarefresh.
""
natutulog naman ako pero iba lang talaga body clock ko at nightshft ako sa part time job ko sa cllcntr 9pm hanggang 6 ng umaga 🤣
"betray you? ive heard that countless times watching drawing tutorials since i started getting interested in drawing. and its for real. syempre hindi lang to sa artists, sa kahit ano pa yan. pero it just hits different when youre in the same line of work."
diba andaming documents kailangan tapos andaming babayaran like di'ba pwedeng enroll nalang agad.
"hello! this is the first time na naka-encounter ng ganito. yung buyer ko na sobrang laking issue sa stem cuts. i don't know anong basis nila for a stem cut, but they kept on insisting na scratch daw yung nasa applehoon ko which is not."
"wala naman. malakas lang kayong magparatang ng walang ebidensya at mahilig kayong gumawa ng kwento. kung manalo man ang sinusuportahan mo, sana di kayo baliwalain kapag nakaupo na. tandaan, magnanakaw is always magnanakaw. bow!"
nd ako ginising mg mga aswang eh.
"eto yung side mo na di nila nakikita, ambot sa mga buang oy mabungol mn og mabuta ig abot sa mga maayong butang na imong mabuhat."
mhaymhay: 'di'ba te no'ng grade 7 section 3 ka. ako section for lang eh nag-mamatter pa ba sections ngayon? saka rhs 'yan bebi 30-40 sections per grade level. mamaw na yung ganan. dahil diyan may treat ka from ate!! gagaling ng mga kapatid ko manang-mana sa'kin so much.
di'ba pwedeng i-fast forward to?
"asus. wala man lang kahit stolen? oh eh di'ba madami daw kayo, according sa mga bbm tards? hahahahahah. dont waste your time on me. cocaine user pa din si bbm para sakin. bye."
"di'ba pwedeng lahat, maybe 3 or for."
"i dont know, why my heart is heavy. unlike the first and second concerts, i was excited for me and myself only. now, nalulungkot ako sa mga apotin ko na di mkanood ng zonecon."
